### ISSUE TITLE
Allocation report is locked

### ISSUE THREAD

**Issue by cathyselmi** [ggowan/easy-nmc#1]
I am trying to finalize the information for Nativity of Christ Greek Orthodox Church and the pencil button says the file is locked. The only remaining information to be included is the breakdown of 2016 stewardship by dollar amount and filling in the remaining names before submitting the form.

Thank you for any help you can offer!
Cathy Selmi
Nativity of Christ Parish Council Treasurer

**Comment by ggowan** [comment]
Hi Cathy, I unlocked the report. Please let me know when you're done and I'll lock it again.
Geoff

**Comment by cathyselmi** [comment]
Thank you Geoff. Unfortunately the power went out in my neighborhood so I'm stuck with my phone and done candles! I'll let you know when I'm able to get back online. 
Cathy

**Comment by cathyselmi** [comment]
Thank you for your help. The power came back on around 2:00 am. 

I have completed the report for the Nativity of Christ parish. 

Cathy
